-- Пользователи
CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(255) NOT NULL UNIQUE,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    birthday date NOT NULL
);

COMMENT ON COLUMN users.id IS 'идентификатор пользователя';
COMMENT ON COLUMN users.login IS 'логин пользователя';
COMMENT ON COLUMN users.email IS 'электронная почта';
COMMENT ON COLUMN users.name IS 'имя для отображения';
COMMENT ON COLUMN users.birthday IS 'дата рождения';


CREATE TABLE IF NOT EXISTS  user_friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    is_confirmed BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_user_friends_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_friends_friend FOREIGN KEY (friend_id) REFERENCES users(id),
    UNIQUE (user_id, friend_id)  -- чтобы не было дублей
);

COMMENT ON COLUMN user_friends.user_id IS 'Идентификатор пользователя, который добавляет в друзья';
COMMENT ON COLUMN user_friends.friend_id IS 'Идентификатор пользователя, которого добавляют в друзья';
COMMENT ON COLUMN user_friends.is_confirmed IS 'Статус подтверждения дружбы (FALSE - ожидает подтверждения, TRUE - дружба подтверждена)';

-- Фильмы
CREATE TABLE IF NOT EXISTS  films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200) DEFAULT '',
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa VARCHAR(50) NOT NULL,
    CONSTRAINT unique_film_name_release UNIQUE (name, release_date)
);

COMMENT ON COLUMN films.id IS 'идентификатор фильма';
COMMENT ON COLUMN films.name IS 'название фильма';
COMMENT ON COLUMN films.description IS 'описание фильма';
COMMENT ON COLUMN films.release_date IS 'дата релиза';
COMMENT ON COLUMN films.duration IS 'продолжительность фильма в минутах';
COMMENT ON COLUMN films.mpa IS 'возрастной рейтинг';


CREATE TABLE IF NOT EXISTS  film_genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER NOT NULL,
    genre VARCHAR(20) NOT NULL,
    CONSTRAINT fk_film_genres_films FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT unique_film_genre UNIQUE (film_id, genre)
);

COMMENT ON COLUMN film_genres.film_id IS 'идентификатор фильма';
COMMENT ON COLUMN films.genre IS 'жанр фильма';


CREATE TABLE IF NOT EXISTS  film_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_film_likes_films FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_film_likes_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT unique_film_user UNIQUE (film_id, user_id)
);

COMMENT ON COLUMN film_likes.film_id IS 'идентификатор фильма';
COMMENT ON COLUMN film_likes.user_id IS 'идентификатор пользователя, поставившего лайк фильму';