-- Пользователи
CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(255) NOT NULL UNIQUE,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS  user_friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    friend_id INTEGER NOT NULL,
    is_confirmed BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_user_friends_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_friends_friend FOREIGN KEY (friend_id) REFERENCES users(id),
    UNIQUE (user_id, friend_id)  -- чтобы не было дублей
);

-- Фильмы
CREATE TABLE IF NOT EXISTS  films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200) DEFAULT '',
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa VARCHAR(50) NOT NULL
    -- Postman tests doesn't work with this constraint!
    -- CONSTRAINT unique_film_name_release UNIQUE (name, release_date)
);

CREATE TABLE IF NOT EXISTS  film_genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER NOT NULL,
    genre VARCHAR(20) NOT NULL,
    CONSTRAINT fk_film_genres_films FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT unique_film_genre UNIQUE (film_id, genre)
);

CREATE TABLE IF NOT EXISTS  film_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT fk_film_likes_films FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_film_likes_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT unique_film_user UNIQUE (film_id, user_id)
);
